# Validate this file using http://lint.travis-ci.org/
language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
install:
  - pip install . --use-mirrors
  - pip install nose mock --use-mirrors
script: nosetests
